web:
  build: ./build
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    PORT: 3000 
db:
  image: mongo
  volumes:
    - "./src:/data/db" 
  ports:
    - "27017:27017"